routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('home');

Auth::routes();

Route::group(['middleware' => ['auth']], function() {
  /* PTA Routes */
  Route::get('/pta/importsyasapta', 'PtaController@getImportForm')->name('pta.formimport');
  Route::post('/pta/import', 'PtaController@import')->name('pta.import');
  Route::post('/pta/autocomplete', 'PtaController@getPtaInList')->name('pta.autocomplete');
  Route::post('/programmes/search', 'ProgrammeController@searchList')->name('programmes.searchList');

  Route::resource('pta', 'PtaController');
  Route::resource('ministeres', 'MinistereController');
  Route::resource('typestructures', 'TypestructureController');
  Route::resource('structures', 'StructureController');
  Route::resource('programmes', 'ProgrammeController');
  Route::resource('objectifs', 'ObjectifController');
  Route::resource('actions', 'ActionController');
  Route::resource('activites', 'ActiviteController');
  Route::resource('taches', 'TacheController');
  Route::resource('evaluations', 'EvaluationController');
  Route::resource('rapports', 'RapportController');

  Route::get('importexcelpta', 'ImportExcelPtaController@importExport')->name('pta.importexcel');

  Route::get('downloadExcel/{type}', 'ImportExcelPtaController@downloadExcel');

  Route::post('importExcel', 'ImportExcelPtaController@importExcel');

});

/*Route::get('/pta/{ptaId}', function () {
    return view('pta.show');
})->name('pta.show');*/

app/Models/Objectif.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model as BaseModel;

class Objectif extends BaseModel
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'objectif';

    /**
     * The database primary key value.
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['code','code_prog', 'abbrev', 'libelle', 'resultat', 'montant', 'nb_mois', 'responsable',
        'associees', 'poids', 'operations', 'niveau', 'mnt_engage', 'taux_engage', 'mnt_ordonance', 'taux_ordonance', 'observations'];

    /**
     * Attributes that aren't in database
     *
     * @var array
     */
    protected $appends = [];
}

app/Http/Controllers/ObjectifController.php
<?php

namespace App\Http\Controllers;

use App\Models\Objectif;
use App\Models\Programme;
use Illuminate\Http\Request;

class ObjectifController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $objectifs = Objectif::orderBy('code')->get();

        $data = compact('objectifs');
        return view('objectifs.list', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $objectif = new Objectif();
        $prog_codes = Programme::orderBy('code')->get()->pluck('code', 'code');
        $mois = array(
            '1' => 'Janvier',
            '2' => 'Février',
            '3' => 'Mars',
            '4' => 'Avril',
            '5' => 'Mai',
            '6' => 'Juin',
            '7' => 'Juillet',
            '8' => 'Août',
            '9' => 'Septembre',
            '10' => 'Octobre',
            '11' => 'Novembre',
            '12' => 'Décembre',
        );

        $data = compact('objectif', 'mois',  'prog_codes');

        return view('objectifs.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $nbr_obj = Objectif::where('code_prog', '=', $request['code_prog'])->count();
        $request['code'] = $request['code_prog'].'-O'.($nbr_obj + 1);
        $request['abbrev'] = 'O'.($nbr_obj + 1);

        $debut = $request['debut'];
        $fin = $request['fin'];

        if($fin < $debut){
            $request['nb_mois'] = (((int)$fin + 12) - (int)$debut) + 1;
        }
        else{
            $request['nb_mois'] = ((int)$fin - (int)$debut) + 1;
        }

        $objectif = Objectif::create($request->all());

        if ($objectif){
            return redirect(route('objectifs.create'));
        }

        $data = compact('objectif');

        return view('objectifs.form', $data);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/objectifs/form.blade.php
<?php
$readonly = "";
$disabled = "";
if ($objectif->id) {  // Cas de la modification ou de la consultation
    if (isset($isView) && $isView) { // Cas de la consultation
        $options = ['class' => 'form-horizontal'];
        $readonly = "readonly";
    } else { // Cas de la modification
        $options = ['route' => ['objectifs.update', $objectif->id], 'method' => 'PUT', 'class' => 'form-horizontal'];
    }
} else { // Cas de l'ajout
    $options = ['route' => ['objectifs.store'], 'method' => 'POST', 'class' => 'form-horizontal'];
    $disabled = "disabled";
}
?>

@extends('layouts.app-content')

@section('page-title')
    Programmes de Travaux Annuels
    <small>Nouvel Objectif</small>
@endsection

@section('breadcrumb')
    @include ('layouts.includes.breadcrumb', ['breadcrumb' => array('Tableau de Bord', 'PTA', 'Nouvel Objectif')])
@endsection

@section('page-content')
    <div class="portlet light">
        {!! Form::model($objectif, $options) !!}
        <div class="form-actions top margin-bottom-20">
            <div class="row">
                <div class="col-md-offset-2 col-md-8">
                    <div class="btn-group">
                        <a href="{{ route('objectifs.index') }}" class="btn btn-default ">
                            <i class="fa fa-arrow-left"></i> Retour
                        </a>
                        @if(isset($isView) && $isView)
                            <a href="{{ route('objectifs.edit', ['id' => $objectif->id]) }}" class="btn btn-primary">
                                <i class="fa fa-edit"></i> Modifier
                            </a>
                        @endif

                        {{--Cacher l'affichage du bouton enregistrer lors de la consultation--}}
                        @unless(isset($isView) && $isView)
                            <button type="submit" class="btn green"><i class="fa fa-save"></i> Enregistrer</button>
                        @endunless
                    </div>
                </div>
            </div>
        </div>
        <div class="form-body">
            @if(isset($message))
                <div class="col-sm-offset-2 col-sm-8 alert alert-{{ $type }}">
                    {{ $message }}
                </div>
            @endif
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-8">
                    {!! Form::label('code', 'Code de l\'objectif', ['class' => 'text-primary label']) !!}
                    {!! Form::text('code', null, ['class' => 'form-control', 'disabled']) !!}
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-8">
                    {!! Form::label('code_pta', 'Code du programme', ['class' => 'text-primary label']) !!} <span
                            class="text-danger">*</span>
                    {!! Form::select('code_prog', $prog_codes, null, ['class' => 'form-control select2', 'placeholder' => 'Veuillez selectionner', 'required' => 'required', $readonly]) !!}
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-8">
                    {!! Form::label('debut', 'Période d\'exécution', ['class' => 'text-primary label']) !!} <span
                            class="text-danger">*</span>
                </div>
                <div class="col-sm-offset-2 col-sm-4">
                    {!! Form::select('debut', $mois, null, ['class' => 'form-control select2', 'placeholder' => 'Veuillez selectionner', 'required' => 'required', $readonly]) !!}
                </div>
                <div class="col-sm-4">
                    {!! Form::select('fin', $mois, null, ['class' => 'form-control select2', 'placeholder' => 'Veuillez selectionner', 'required' => 'required', $readonly]) !!}
                </div>

            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-4">
                    {!! Form::label('montant', 'Montant alloué', ['class' => 'text-primary label']) !!}
                    <span class="text-danger">*</span>
                    {!! Form::number('montant', null, ['class' => 'form-control', 'min' => '0', 'required' => 'required', $readonly]) !!}
                </div>
                <div class="col-sm-4">
                    {!! Form::label('poids', 'Poids Global', ['class' => 'text-primary label']) !!}
                    <span class="text-danger">*</span>
                    {!! Form::number('poids', null, ['class' => 'form-control', 'min' => '0', 'max' => '100', 'required' => 'required', $readonly]) !!}
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-8">
                    {!! Form::label('libelle', 'Libellé de l\'objectif', ['class' => 'text-primary label']) !!}
                    <span class="text-danger">*</span>
                    {!! Form::textarea('libelle', null, ['class' => 'form-control', 'rows' => '3', 'required' => 'required', $readonly]) !!}
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-8">
                    {!! Form::label('resultat', 'Résultat attendu', ['class' => 'text-primary label']) !!}
                    <span class="text-danger">*</span>
                    {!! Form::textarea('resultat', null, ['class' => 'form-control', 'rows' => '3', 'required' => 'required', $readonly]) !!}
                </div>
            </div>

            @unless(isset($isView) && $isView)
                <div class="row">
                    <div class="col-md-offset-2 col-md-8">
                        <span class="text-danger required-asterik">*</span> Champs obligatoires
                    </div>
                </div>
            @endunless
        </div>
        {!! Form::close() !!}
    </div>
@endsection

resources/views/objectifs/list.blade.php
@extends('layouts.app-content')

@section('page-title')
    Programmes de Travaux Annuels
    <small>Liste des objectifs & résultats</small>
@endsection

@section('breadcrumb')
    @include ('layouts.includes.breadcrumb', ['breadcrumb' => array('Tableau de Bord', 'PTA', 'Liste des objectifs & résultats')])
@endsection

@section('page-content')
    <div class="row margin-top-10">
        <div class="col-xs-12">
            <!-- BEGIN PORTLET-->
            <div class="portlet light ">
                <div class="portlet-body">
                    <div class="tools" >
                        <a href="{{ route('objectifs.create') }}" class="btn btn-success" style=""><i class="glyphicon glyphicon-plus"></i>
                            Ajouter
                        </a>
                    </div>
                    <hr>
                    <div class="table-responsive">
                        <table id="dataTable" class="table table-hover table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>Identifiant</th>
                                <th>Objectif</th>
                                <th>Résultat</th>
                                <th>Période</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($objectifs as $objectif)
                                <tr>
                                    <td>{{ $objectif->code }}</td>
                                    <td>{{ $objectif->libelle }}</td>
                                    <td>{{ $objectif->resultat }}</td>
                                    <td>{{ $objectif->nb_mois }}</td>
                                    <td>
                                        {{--<a href="{{ route('objectifs.destroy', ['id' => $objectif->id]) }}" class="btn-sm btn-danger"
                                           title="Supprimer"><i class="fa fa-trash-o"></i></a>--}}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
@endsection