routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('home');

Auth::routes();

Route::group(['middleware' => ['auth']], function() {
  /* PTA Routes */
  Route::get('/pta/importsyasapta', 'PtaController@getImportForm')->name('pta.formimport');
  Route::post('/pta/import', 'PtaController@import')->name('pta.import');
  Route::post('/pta/autocomplete', 'PtaController@getPtaInList')->name('pta.autocomplete');
  Route::post('/programmes/search', 'ProgrammeController@searchList')->name('programmes.searchList');

  Route::resource('pta', 'PtaController');
  Route::resource('ministeres', 'MinistereController');
  Route::resource('typestructures', 'TypestructureController');
  Route::resource('structures', 'StructureController');
  Route::resource('programmes', 'ProgrammeController');
  Route::resource('objectifs', 'ObjectifController');
  Route::resource('actions', 'ActionController');
  Route::resource('activites', 'ActiviteController');
  Route::resource('taches', 'TacheController');
  Route::resource('evaluations', 'EvaluationController');
  Route::resource('rapports', 'RapportController');

  Route::get('importexcelpta', 'ImportExcelPtaController@importExport')->name('pta.importexcel');

  Route::get('downloadExcel/{type}', 'ImportExcelPtaController@downloadExcel');

  Route::post('importExcel', 'ImportExcelPtaController@importExcel');

});

/*Route::get('/pta/{ptaId}', function () {
    return view('pta.show');
})->name('pta.show');*/

app/Models/Ministere.php
<?php

namespace App\Models;

use App\Models\Model;
class Ministere extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'ministere';

    /**
     * The database primary key value.
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['code', 'libelle'];

    /**
     * Attributes that aren't in database
     *
     * @var array
     */
    protected $appends = [];

}

app/Http/Controllers/MinistereController.php
<?php

namespace App\Http\Controllers;

use App\Models\Ministere;
use Illuminate\Http\Request;

class MinistereController extends Controller
{

    public function __construct(Request $request)
    {
        parent::__construct($request);
        //
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $ministeres = Ministere::orderBy('code')->get();

        $data = compact('ministeres');
        return view('ministeres.list', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $ministere = new Ministere();

        $data = compact('ministere');

        return view('ministeres.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $ministere = Ministere::create($request->all());

        if ($ministere){
            return redirect(route('ministeres.create'));
        }

        $data = compact('ministere');

        return view('ministeres.form', $data);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/ministeres/form.blade.php
<?php
$readonly = "";
$disabled = "";
if ($ministere->id) {  // Cas de la modification ou de la consultation
    if (isset($isView) && $isView) { // Cas de la consultation
        $options = ['class' => 'form-horizontal'];
        $readonly = "readonly";
    } else { // Cas de la modification
        $options = ['route' => ['ministeres.update', $ministere->id], 'method' => 'PUT', 'class' => 'form-horizontal'];
    }
} else { // Cas de l'ajout
    $options = ['route' => ['ministeres.store'], 'method' => 'POST', 'class' => 'form-horizontal'];
    $disabled = "disabled";
}
?>

@extends('layouts.app-content')

@section('page-title')
    Paramètres de base
    <small>Ajout d'un nouveau ministère</small>
@endsection

@section('breadcrumb')
    @include ('layouts.includes.breadcrumb', ['breadcrumb' => array('Tableau de Bord', 'Paramètres de base', 'Nouveau ministère')])
@endsection

@section('page-content')
    <div class="portlet light">
        {!! Form::model($ministere, $options) !!}
        <div class="form-actions top margin-bottom-20">
            <div class="row">
                <div class="col-md-offset-2 col-md-8">
                    <div class="btn-group">
                        <a href="{{ route('ministeres.index') }}" class="btn btn-default ">
                            <i class="fa fa-arrow-left"></i> Retour
                        </a>
                        @if(isset($isView) && $isView)
                            <a href="{{ route('ministeres.edit', ['id' => $ministere->id]) }}" class="btn btn-primary">
                                <i class="fa fa-edit"></i> Modifier
                            </a>
                        @endif

                        {{--Cacher l'affichage du bouton enregistrer lors de la consultation--}}
                        @unless(isset($isView) && $isView)
                            <button type="submit" class="btn green"><i class="fa fa-save"></i> Enregistrer</button>
                        @endunless
                    </div>
                </div>
            </div>
        </div>
        <div class="form-body">
            @if(isset($message))
                <div class="col-sm-offset-2 col-sm-8 alert alert-{{ $type }}">
                    {{ $message }}
                </div>
            @endif
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-8">
                    {!! Form::label('code', 'Code du ministère', ['class' => 'text-primary label']) !!}
                    {!! Form::text('code', null, ['class' => 'form-control', $readonly]) !!}
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-8">
                    {!! Form::label('libelle', 'Libellé du ministère', ['class' => 'text-primary label']) !!}
                    {!! Form::text('libelle', null, ['class' => 'form-control', $readonly]) !!}
                </div>
            </div>

            @unless(isset($isView) && $isView)
                <div class="row">
                    <div class="col-md-offset-2 col-md-8">
                        <span class="text-danger required-asterik">*</span> Champs obligatoires
                    </div>
                </div>
            @endunless
        </div>
        {!! Form::close() !!}
    </div>
@endsection

resources/views/ministeres/list.blade.php
@extends('layouts.app-content')

@section('page-title')
    Paramètres de base
    <small>Liste des ministères</small>
@endsection

@section('breadcrumb')
    @include ('layouts.includes.breadcrumb', ['breadcrumb' => array('Tableau de Bord', 'Paramètres de base', 'Liste des ministères')])
@endsection


@section('page-content')
    <div class="row margin-top-10">
        <div class="col-xs-12">
            <!-- BEGIN PORTLET-->
            <div class="portlet light ">
                <div class="portlet-body">
                    <div class="tools">
                        <a href="{{ route('ministeres.create') }}" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i>
                            Ajouter
                        </a>
                    </div>
                    <hr>
                    <div class="table-responsive">
                        <table class="table table-hover table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Code</th>
                                <th>Ministère</th>
                                <!--th>Actions</th-->
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($ministeres as $ministere)
                                <?php $compteur = 1; ?>
                                <tr>
                                    <td>{{ $ministere->id }}</td>
                                    <td>{{ $ministere->code }}</td>
                                    <td>{{ $ministere->libelle }}</td>
                                    <!--td>
                                        <a href="{{ route('ministeres.destroy', ['id' => $ministere->id]) }}" class="btn-sm btn-danger"
                                           title="Supprimer"><i class="fa fa-trash-o"></i></a>
                                    </td-->
                                </tr>
                                <?php $compteur ++; ?>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
@endsection